title: Things Devs Say
author: Nick Patterson
email: nkpatterson@github.com
description: > # this means to ignore newlines until "baseurl:"
  Keeping track of all the wacky stuff developers say

# social links
twitter_username: nickpatterson
github_username:  nkpatterson

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
